spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-collect-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: xyz.yihuier.logcollector.domain
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: xyz.yihuier.logcollector.domain
    template:
      default-topic: log-collect-topic
  elasticsearch:
    uris: http://localhost:9200
server:
  port: 8888

